language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
install:
  - |
    cd python_bindings
    python -m pip install .

script:
  - |
    cd python_bindings
    pip install --install-option test
